import datasets
from mteb import TaskMetadata
import pandas as pd
from tabulate import tabulate

_MASSIVE_LANGUAGES = {
    "af": ["afr-Latn"],
    "am": ["amh-Ethi"],
    "ar": ["ara-Arab"],
    "az": ["aze-Latn"],
    "bn": ["ben-Beng"],
    "cy": ["cym-Latn"],
    "da": ["dan-Latn"],
    "de": ["deu-Latn"],
    "el": ["ell-Grek"],
    "en": ["eng-Latn"],
    "es": ["spa-Latn"],
    "fa": ["fas-Arab"],
    "fi": ["fin-Latn"],
    "fr": ["fra-Latn"],
    "he": ["heb-Hebr"],
    "hi": ["hin-Deva"],
    "hu": ["hun-Latn"],
    "hy": ["hye-Armn"],
    "id": ["ind-Latn"],
    "is": ["isl-Latn"],
    "it": ["ita-Latn"],
    "ja": ["jpn-Jpan"],
    "jv": ["jav-Latn"],
    "ka": ["kat-Geor"],
    "km": ["khm-Khmr"],
    "kn": ["kan-Knda"],
    "ko": ["kor-Kore"],
    "lv": ["lav-Latn"],
    "ml": ["mal-Mlym"],
    "mn": ["mon-Cyrl"],
    "ms": ["msa-Latn"],
    "my": ["mya-Mymr"],
    "nb": ["nob-Latn"],
    "nl": ["nld-Latn"],
    "pl": ["pol-Latn"],
    "pt": ["por-Latn"],
    "ro": ["ron-Latn"],
    "ru": ["rus-Cyrl"],
    "sl": ["slv-Latn"],
    "sq": ["sqi-Latn"],
    "sv": ["swe-Latn"],
    "sw": ["swa-Latn"],
    "ta": ["tam-Taml"],
    "te": ["tel-Telu"],
    "th": ["tha-Thai"],
    "tl": ["tgl-Latn"],
    "tr": ["tur-Latn"],
    "ur": ["urd-Arab"],
    "vi": ["vie-Latn"],
    "zh-CN": ["cmo-Hans"],
    "zh-TW": ["cmo-Hant"],
}

_STS22_LANGUAGES = {
    "en": ["eng-Latn"],
    "de": ["deu-Latn"],
    "es": ["spa-Latn"],
    "pl": ["pol-Latn"],
    "tr": ["tur-Latn"],
    "ar": ["ara-Arab"],
    "ru": ["rus-Cyrl"],
    "zh": ["cmn-Hans"],
    "fr": ["fra-Latn"],
    "de-en": ["deu-Latn", "eng-Latn"],
    "es-en": ["spa-Latn", "eng-Latn"],
    "it": ["ita-Latn"],
    "pl-en": ["pol-Latn", "eng-Latn"],
    "zh-en": ["cmn-Hans", "eng-Latn"],
    "es-it": ["spa-Latn", "ita-Latn"],
    "de-fr": ["deu-Latn", "fra-Latn"],
    "de-pl": ["deu-Latn", "pol-Latn"],
    "fr-pl": ["fra-Latn", "pol-Latn"],
}

tasks_metadata = {
    "CBD": TaskMetadata(
        name="CBD",
        description="Polish Tweets annotated for cyberbullying detection. Creation procedure: [] #unbalanced",
        reference="http://2019.poleval.pl/files/poleval2019.pdf",
        dataset={
            "path": "PL-MTEB/cbd",
            "revision": "36ddb419bcffe6a5374c3891957912892916f28d",
        },
        type="Classification",
        category="s2s",
        eval_splits=["test"],
        eval_langs=["pol-Latn"],
        main_score="accuracy",
        date=None,
        form=None,
        domains=["Social"],
        task_subtypes=None,
        license="bsd-3-clause",
        socioeconomic_status=None,
        annotations_creators=None,
        dialect=None,
        text_creation=None,
        bibtex_citation="""@proceedings{ogr:kob:19:poleval,
                          editor    = {Maciej Ogrodniczuk and Łukasz Kobyliński},
                          title     = {{Proceedings of the PolEval 2019 Workshop}},
                          year      = {2019},
                          address   = {Warsaw, Poland},
                          publisher = {Institute of Computer Science, Polish Academy of Sciences},
                          url       = {http://2019.poleval.pl/files/poleval2019.pdf},
                          isbn      = "978-83-63159-28-3"}
                        }""",
        n_samples={"train": 10000, "test": 1000},
        avg_character_length={"train": 95.3, "test": 93.2},
    ),
    "PolEmo2.0-IN": TaskMetadata(
        name="PolEmo2.0-IN",
        description="A collection of Polish online reviews from four domains: medicine, hotels, products and "
                    "school. The PolEmo2.0-IN task is to predict the sentiment of in-domain (medicine and hotels) reviews. #unbalanced",
        reference="https://aclanthology.org/K19-1092.pdf",
        dataset={
            "path": "PL-MTEB/polemo2_in",
            "revision": "d90724373c70959f17d2331ad51fb60c71176b03",
        },
        type="Classification",
        category="s2s",
        eval_splits=["test"],
        eval_langs=["pol-Latn"],
        main_score="accuracy",
        date=None,
        form=None,
        domains=["Reviews"],
        task_subtypes=None,
        license="cc-by-nc-sa-4.0",
        socioeconomic_status=None,
        annotations_creators=None,
        dialect=None,
        text_creation=None,
        bibtex_citation="""@inproceedings{kocon-etal-2019-multi,
                            title = "Multi-Level Sentiment Analysis of {P}ol{E}mo 2.0: Extended Corpus of Multi-Domain Consumer Reviews",
                            author = "Koco{\'n}, Jan  and
                              Mi{\l}kowski, Piotr  and
                              Za{\'s}ko-Zieli{\'n}ska, Monika",
                            booktitle = "Proceedings of the 23rd Conference on Computational Natural Language Learning (CoNLL)",
                            month = nov,
                            year = "2019",
                            address = "Hong Kong, China",
                            publisher = "Association for Computational Linguistics",
                            url = "https://aclanthology.org/K19-1092",
                            doi = "10.18653/v1/K19-1092",
                            pages = "980--991",
                            abstract = "In this article we present an extended version of PolEmo {--} a corpus of consumer reviews from 4 domains: medicine, hotels, products and school. Current version (PolEmo 2.0) contains 8,216 reviews having 57,466 sentences. Each text and sentence was manually annotated with sentiment in 2+1 scheme, which gives a total of 197,046 annotations. We obtained a high value of Positive Specific Agreement, which is 0.91 for texts and 0.88 for sentences. PolEmo 2.0 is publicly available under a Creative Commons copyright license. We explored recent deep learning approaches for the recognition of sentiment, such as Bi-directional Long Short-Term Memory (BiLSTM) and Bidirectional Encoder Representations from Transformers (BERT).",
                        }""",
        n_samples={"train": 5780, "test": 722},
        avg_character_length={"train": 738.3, "test": 741.4},
    ),
    "PolEmo2.0-OUT": TaskMetadata(
        name="PolEmo2.0-OUT",
        description="A collection of Polish online reviews from four domains: medicine, hotels, products and "
                    "school. The PolEmo2.0-OUT task is to predict the sentiment of out-of-domain (products and "
                    "school) reviews using models train on reviews from medicine and hotels domains. #unbalanced",
        reference="https://aclanthology.org/K19-1092.pdf",
        dataset={
            "path": "PL-MTEB/polemo2_out",
            "revision": "6a21ab8716e255ab1867265f8b396105e8aa63d4",
        },
        type="Classification",
        category="s2s",
        eval_splits=["test"],
        eval_langs=["pol-Latn"],
        main_score="accuracy",
        date=None,
        form=None,
        domains=["Reviews"],
        task_subtypes=None,
        license="cc-by-nc-sa-4.0",
        socioeconomic_status=None,
        annotations_creators=None,
        dialect=None,
        text_creation=None,
        bibtex_citation=None,
        n_samples={"train": 5780, "test": 722},
        avg_character_length={"train": 740.3, "test": 756.2},
    ),
    "AllegroReviews": TaskMetadata(
        name="AllegroReviews",
        description="A Polish dataset for sentiment classification on reviews from e-commerce marketplace Allegro. #unbalanced",
        reference="https://aclanthology.org/2020.acl-main.111.pdf",
        dataset={
            "path": "PL-MTEB/allegro-reviews",
            "revision": "b89853e6de927b0e3bfa8ecc0e56fe4e02ceafc6",
        },
        type="Classification",
        category="s2s",
        eval_splits=["test"],
        eval_langs=["pol-Latn"],
        main_score="accuracy",
        date=None,
        form=None,
        domains=["Reviews"],
        task_subtypes=None,
        license="cc-by-sa-4.0",
        socioeconomic_status=None,
        annotations_creators=None,
        dialect=None,
        text_creation=None,
        bibtex_citation=None,
        n_samples={"train": 9580, "test": 1006},
        avg_character_length={"train": 475.6, "test": 477.2},
    ),
    "PAC": TaskMetadata(
        name="PAC",
        description="Polish Abusive Clauses Dataset #unbalanced",
        reference="https://arxiv.org/pdf/2211.13112.pdf",
        dataset={
            "path": "laugustyniak/abusive-clauses-pl",
            "revision": "fc69d1c153a8ccdcf1eef52f4e2a27f88782f543",
        },
        type="Classification",
        category="p2p",
        eval_splits=["test"],
        eval_langs=["pol-Latn"],
        main_score="accuracy",
        date=None,
        form=None,
        domains=["Legal"],
        task_subtypes=None,
        license="cc-by-nc-sa-4.0",
        socioeconomic_status=None,
        annotations_creators=None,
        dialect=None,
        text_creation=None,
        bibtex_citation=None,
        n_samples={"train": 4284, "test": 3453},
        avg_character_length={"train": 182.5, "test": 185.3},
    ),
    "MassiveIntentClassification": TaskMetadata(
        name="MassiveIntentClassification",
        dataset={
            "path": "mteb/amazon_massive_intent",
            "revision": "4672e20407010da34463acc759c162ca9734bca6",
        },
        description="MASSIVE: A 1M-Example Multilingual Natural Language Understanding Dataset with 51 Typologically-Diverse Languages #unbalanced",
        reference="https://arxiv.org/abs/2204.08582#:~:text=MASSIVE%20contains%201M%20realistic%2C%20parallel,diverse%20languages%20from%2029%20genera.",
        category="s2s",
        type="Classification",
        eval_splits=["validation", "test"],
        eval_langs=_MASSIVE_LANGUAGES,
        main_score="accuracy",
        date=None,
        form=None,
        domains=["Spoken"],
        task_subtypes=None,
        license="cc-by-4.0",
        socioeconomic_status=None,
        annotations_creators=None,
        dialect=None,
        text_creation=None,
        bibtex_citation="""@misc{fitzgerald2022massive,
                          title={MASSIVE: A 1M-Example Multilingual Natural Language Understanding Dataset with 51 Typologically-Diverse Languages}, 
                          author={Jack FitzGerald and Christopher Hench and Charith Peris and Scott Mackie and Kay Rottmann and Ana Sanchez and Aaron Nash and Liam Urbach and Vishesh Kakarala and Richa Singh and Swetha Ranganath and Laurie Crist and Misha Britan and Wouter Leeuwis and Gokhan Tur and Prem Natarajan},
                          year={2022},
                          eprint={2204.08582},
                          archivePrefix={arXiv},
                          primaryClass={cs.CL}
                    }""",
        n_samples={"train": 11500, "validation": 2033, "test": 2974},
        avg_character_length={"train": 34.5, "validation": 34.8, "test": 34.6},
    ),
    "MassiveScenarioClassification": TaskMetadata(
        name="MassiveScenarioClassification",
        dataset={
            "path": "mteb/amazon_massive_scenario",
            "revision": "fad2c6e8459f9e1c45d9315f4953d921437d70f8",
        },
        description="MASSIVE: A 1M-Example Multilingual Natural Language Understanding Dataset with 51 Typologically-Diverse Languages #unbalanced",
        reference="https://arxiv.org/abs/2204.08582#:~:text=MASSIVE%20contains%201M%20realistic%2C%20parallel,diverse%20languages%20from%2029%20genera.",
        category="s2s",
        type="Classification",
        eval_splits=["validation", "test"],
        eval_langs=_MASSIVE_LANGUAGES,
        main_score="accuracy",
        date=None,
        form=None,
        domains=["Spoken"],
        task_subtypes=None,
        license="cc-by-4.0",
        socioeconomic_status=None,
        annotations_creators=None,
        dialect=None,
        text_creation=None,
        bibtex_citation="""@misc{fitzgerald2022massive,
                          title={MASSIVE: A 1M-Example Multilingual Natural Language Understanding Dataset with 51 Typologically-Diverse Languages}, 
                          author={Jack FitzGerald and Christopher Hench and Charith Peris and Scott Mackie and Kay Rottmann and Ana Sanchez and Aaron Nash and Liam Urbach and Vishesh Kakarala and Richa Singh and Swetha Ranganath and Laurie Crist and Misha Britan and Wouter Leeuwis and Gokhan Tur and Prem Natarajan},
                          year={2022},
                          eprint={2204.08582},
                          archivePrefix={arXiv},
                          primaryClass={cs.CL}
                    }""",
        n_samples={"train": 11500, "validation": 2033, "test": 2974},
        avg_character_length={"train": 34.5, "validation": 34.8, "test": 34.6},
    ),
    "SciField": TaskMetadata(
        name="SciField",
        description="Based on the paragraph from the coursebook, identify the scientific field from which it comes. "
                    "Available fields are: chemistry, physics, mathematics, geology  and social science. #unbalanced",
        reference="https://huggingface.co/datasets/rafalposwiata/open-coursebooks-pl",
        dataset={
            "path": "PL-MTEB/scifield",
            "revision": "8064b4442da038aa0482a2542370f9a2441cc50a",
        },
        type="Classification",
        category="s2s",
        eval_splits=["test"],
        eval_langs=["pol-Latn"],
        main_score="accuracy",
        date=None,
        form=None,
        domains=["Academic"],
        task_subtypes=None,
        license="cc-by-sa-4.0",
        socioeconomic_status="high",
        annotations_creators="derived",
        dialect=[],
        text_creation="found",
        bibtex_citation="",
        n_samples={"train": 5751, "test": 1438},
        avg_character_length={"train": 431.6, "test": 430.4},
    ),
    "EightTagsClustering": TaskMetadata(
        name="EightTagsClustering",
        description="Clustering of headlines from social media posts in Polish belonging to 8 categories: film, history, "
                    "food, medicine, motorization, work, sport and technology.",
        reference="https://aclanthology.org/2020.lrec-1.207.pdf",
        dataset={
            "path": "PL-MTEB/8tags-clustering",
            "revision": "78b962b130c6690659c65abf67bf1c2f030606b6",
        },
        type="Clustering",
        category="s2s",
        eval_splits=["test"],
        eval_langs=["pol-Latn"],
        main_score="v_measure",
        date=("2019-01-01", "2020-05-01"),
        form=["written"],
        domains=["Social"],
        task_subtypes=["Topic classification", "Thematic clustering"],
        license="GPL-3.0",
        socioeconomic_status="mixed",
        annotations_creators="derived",
        dialect=[],
        text_creation="found",
        bibtex_citation="""@inproceedings{dadas-etal-2020-evaluation,
            title = "Evaluation of Sentence Representations in {P}olish",
            author = "Dadas, Slawomir  and
            Pere{\l}kiewicz, Micha{\l}  and
            Po{\'s}wiata, Rafa{\l}",
            editor = "Calzolari, Nicoletta  and
            B{\'e}chet, Fr{\'e}d{\'e}ric  and
            Blache, Philippe  and
            Choukri, Khalid  and
            Cieri, Christopher  and
            Declerck, Thierry  and
            Goggi, Sara  and
            Isahara, Hitoshi  and
            Maegaard, Bente  and
            Mariani, Joseph  and
            Mazo, H{\'e}l{\`e}ne  and
            Moreno, Asuncion  and
            Odijk, Jan  and
            Piperidis, Stelios",
            booktitle = "Proceedings of the Twelfth Language Resources and Evaluation Conference",
            month = may,
            year = "2020",
            address = "Marseille, France",
            publisher = "European Language Resources Association",
            url = "https://aclanthology.org/2020.lrec-1.207",
            pages = "1674--1680",
            abstract = "Methods for learning sentence representations have been actively developed in recent years. However, the lack of pre-trained models and datasets annotated at the sentence level has been a problem for low-resource languages such as Polish which led to less interest in applying these methods to language-specific tasks. In this study, we introduce two new Polish datasets for evaluating sentence embeddings and provide a comprehensive evaluation of eight sentence representation methods including Polish and multilingual models. We consider classic word embedding models, recently developed contextual embeddings and multilingual sentence encoders, showing strengths and weaknesses of specific approaches. We also examine different methods of aggregating word vectors into a single sentence vector.",
            language = "English",
            ISBN = "979-10-95546-34-4",
        }""",
        n_samples={"test": 49373},
        avg_character_length={"test": 78.23}
    ),
    "PlscClusteringS2S": TaskMetadata(
        name="PlscClusteringS2S",
        description="Clustering of Polish article titles from Library of Science (https://bibliotekanauki.pl/), either "
                    "on the scientific field or discipline.",
        reference="https://huggingface.co/datasets/rafalposwiata/plsc",
        dataset={
            "path": "PL-MTEB/plsc-clustering-s2s",
            "revision": "39bcadbac6b1eddad7c1a0a176119ce58060289a",
        },
        type="Clustering",
        category="s2s",
        eval_splits=["test"],
        eval_langs=["pol-Latn"],
        main_score="v_measure",
        date=("2022-04-04", "2023-09-12"),
        form=["written"],
        domains=["Academic"],
        task_subtypes=["Topic classification"],
        license="cc0-1.0",
        socioeconomic_status="high",
        annotations_creators="derived",
        dialect=[],
        text_creation="found",
        bibtex_citation="",
        n_samples={"test": 17534},
        avg_character_length={"test": 84.34},
    ),
    "PlscClusteringP2P": TaskMetadata(
        name="PlscClusteringP2P",
        description="Clustering of Polish article titles+abstracts from Library of Science "
                    "(https://bibliotekanauki.pl/), either on the scientific field or discipline.",
        reference="https://huggingface.co/datasets/rafalposwiata/plsc",
        dataset={
            "path": "PL-MTEB/plsc-clustering-p2p",
            "revision": "8436dd4c05222778013d6642ee2f3fa1722bca9b",
        },
        type="Clustering",
        category="s2s",
        eval_splits=["test"],
        eval_langs=["pol-Latn"],
        main_score="v_measure",
        date=("2022-04-04", "2023-09-12"),
        form=["written"],
        domains=["Academic"],
        task_subtypes=["Topic classification"],
        license="cc0-1.0",
        socioeconomic_status="high",
        annotations_creators="derived",
        dialect=[],
        text_creation="found",
        bibtex_citation="",
        n_samples={"test": 17537},
        avg_character_length={"test": 1023.21},
    ),
    "WikinewsPlClusteringS2S": TaskMetadata(
        name="WikinewsPlClusteringS2S",
        description="",
        reference="https://huggingface.co/datasets/rafalposwiata/wikinews-pl",
        dataset={
            "path": "PL-MTEB/wikinews-pl-clustering-s2s",
            "revision": "2355f412aa5b735fc66cbfe8dff766c49fb45a5d",
        },
        type="Clustering",
        category="s2s",
        eval_splits=["test"],
        eval_langs=["pol-Latn"],
        main_score="v_measure",
        date=("2020-01-01", "2024-06-05"),
        form=["written"],
        domains=["News"],
        task_subtypes=["Topic classification"],
        license="cc-by-2.5",
        socioeconomic_status="high",
        annotations_creators="derived",
        dialect=[],
        text_creation="found",
        bibtex_citation="",
        n_samples={"test": 4477},
        avg_character_length={"test": 60.18},
    ),
    "WikinewsPlClusteringP2P": TaskMetadata(
        name="WikinewsPlClusteringP2P",
        description="",
        reference="https://huggingface.co/datasets/rafalposwiata/wikinews-pl",
        dataset={
            "path": "PL-MTEB/wikinews-pl-clustering-p2p",
            "revision": "8f10d8e9d094ff9f2a8e99e645ad22eb745eb3cf",
        },
        type="Clustering",
        category="p2p",
        eval_splits=["test"],
        eval_langs=["pol-Latn"],
        main_score="v_measure",
        date=("2020-01-01", "2024-06-05"),
        form=["written"],
        domains=["News"],
        task_subtypes=["Topic classification"],
        license="cc-by-2.5",
        socioeconomic_status="high",
        annotations_creators="derived",
        dialect=[],
        text_creation="found",
        bibtex_citation="",
        n_samples={"test": 4477},
        avg_character_length={"test": 1127.31},
    ),
    "SICK-E-PL": TaskMetadata(
        name="SICK-E-PL",
        dataset={
            "path": "PL-MTEB/sicke-pl-pairclassification",
            "revision": "71bba34b0ece6c56dfcf46d9758a27f7a90f17e9",
        },
        description="Polish version of SICK dataset for textual entailment.",
        reference="https://aclanthology.org/2020.lrec-1.207",
        category="s2s",
        type="PairClassification",
        eval_splits=["test"],
        eval_langs=["pol-Latn"],
        main_score="ap",
        date=None,
        form=None,
        domains=["Web"],
        task_subtypes=None,
        license="cc-by-nc-sa-3.0",
        socioeconomic_status=None,
        annotations_creators=None,
        dialect=None,
        text_creation=None,
        bibtex_citation="""@inproceedings{dadas-etal-2020-evaluation,
            title = "Evaluation of Sentence Representations in {P}olish",
            author = "Dadas, Slawomir  and
              Pere{\l}kiewicz, Micha{\l}  and
              Po{\'s}wiata, Rafa{\l}",
            editor = "Calzolari, Nicoletta  and
              B{\'e}chet, Fr{\'e}d{\'e}ric  and
              Blache, Philippe  and
              Choukri, Khalid  and
              Cieri, Christopher  and
              Declerck, Thierry  and
              Goggi, Sara  and
              Isahara, Hitoshi  and
              Maegaard, Bente  and
              Mariani, Joseph  and
              Mazo, H{\'e}l{\`e}ne  and
              Moreno, Asuncion  and
              Odijk, Jan  and
              Piperidis, Stelios",
            booktitle = "Proceedings of the Twelfth Language Resources and Evaluation Conference",
            month = may,
            year = "2020",
            address = "Marseille, France",
            publisher = "European Language Resources Association",
            url = "https://aclanthology.org/2020.lrec-1.207",
            pages = "1674--1680",
            abstract = "Methods for learning sentence representations have been actively developed in recent years. However, the lack of pre-trained models and datasets annotated at the sentence level has been a problem for low-resource languages such as Polish which led to less interest in applying these methods to language-specific tasks. In this study, we introduce two new Polish datasets for evaluating sentence embeddings and provide a comprehensive evaluation of eight sentence representation methods including Polish and multilingual models. We consider classic word embedding models, recently developed contextual embeddings and multilingual sentence encoders, showing strengths and weaknesses of specific approaches. We also examine different methods of aggregating word vectors into a single sentence vector.",
            language = "English",
            ISBN = "979-10-95546-34-4",
        }""",
        n_samples={"test": 1000},
        avg_character_length={"test": 42.8},
    ),
    "PPC": TaskMetadata(
        name="PPC",
        dataset={
            "path": "PL-MTEB/ppc-pairclassification",
            "revision": "2c7d2df57801a591f6b1e3aaf042e7a04ec7d9f2",
        },
        description="Polish Paraphrase Corpus",
        reference="https://arxiv.org/pdf/2207.12759.pdf",
        category="s2s",
        type="PairClassification",
        eval_splits=["test"],
        eval_langs=["pol-Latn"],
        main_score="ap",
        date=None,
        form=None,
        domains=["Web"],
        task_subtypes=None,
        license="cc-by-nc-sa-4.0",
        socioeconomic_status=None,
        annotations_creators=None,
        dialect=None,
        text_creation=None,
        bibtex_citation=None,
        n_samples={"test": 1000},
        avg_character_length={"test": 98.2},
    ),
    "CDSC-E": TaskMetadata(
        name="CDSC-E",
        dataset={
            "path": "PL-MTEB/cdsce-pairclassification",
            "revision": "0a3d4aa409b22f80eb22cbf59b492637637b536d",
        },
        description="Compositional Distributional Semantics Corpus for textual entailment.",
        reference="https://aclanthology.org/P17-1073.pdf",
        category="s2s",
        type="PairClassification",
        eval_splits=["test"],
        eval_langs=["pol-Latn"],
        main_score="ap",
        date=None,
        form=None,
        domains=["Web"],
        task_subtypes=None,
        license="cc-by-nc-sa-4.0",
        socioeconomic_status=None,
        annotations_creators=None,
        dialect=None,
        text_creation=None,
        bibtex_citation="""@inproceedings{wroblewska-krasnowska-kieras-2017-polish,
            title = "{P}olish evaluation dataset for compositional distributional semantics models",
            author = "Wr{\'o}blewska, Alina  and
              Krasnowska-Kiera{\'s}, Katarzyna",
            editor = "Barzilay, Regina  and
              Kan, Min-Yen",
            booktitle = "Proceedings of the 55th Annual Meeting of the Association for Computational Linguistics (Volume 1: Long Papers)",
            month = jul,
            year = "2017",
            address = "Vancouver, Canada",
            publisher = "Association for Computational Linguistics",
            url = "https://aclanthology.org/P17-1073",
            doi = "10.18653/v1/P17-1073",
            pages = "784--792",
            abstract = "The paper presents a procedure of building an evaluation dataset. for the validation of compositional distributional semantics models estimated for languages other than English. The procedure generally builds on steps designed to assemble the SICK corpus, which contains pairs of English sentences annotated for semantic relatedness and entailment, because we aim at building a comparable dataset. However, the implementation of particular building steps significantly differs from the original SICK design assumptions, which is caused by both lack of necessary extraneous resources for an investigated language and the need for language-specific transformation rules. The designed procedure is verified on Polish, a fusional language with a relatively free word order, and contributes to building a Polish evaluation dataset. The resource consists of 10K sentence pairs which are human-annotated for semantic relatedness and entailment. The dataset may be used for the evaluation of compositional distributional semantics models of Polish.",
        }""",
        n_samples={"test": 4910},
        avg_character_length={"test": 75.24},
    ),
    "PSC": TaskMetadata(
        name="PSC",
        dataset={
            "path": "PL-MTEB/psc-pairclassification",
            "revision": "d05a294af9e1d3ff2bfb6b714e08a24a6cabc669",
        },
        description="Polish Summaries Corpus",
        reference="http://www.lrec-conf.org/proceedings/lrec2014/pdf/1211_Paper.pdf",
        category="s2s",
        type="PairClassification",
        eval_splits=["test"],
        eval_langs=["pol-Latn"],
        main_score="ap",
        date=None,
        form=None,
        domains=["News"],
        task_subtypes=None,
        license="cc-by-sa-3.0",
        socioeconomic_status=None,
        annotations_creators=None,
        dialect=None,
        text_creation=None,
        bibtex_citation="""@inproceedings{ogrodniczuk-kopec-2014-polish,
            title = "The {P}olish Summaries Corpus",
            author = "Ogrodniczuk, Maciej  and
              Kope{\'c}, Mateusz",
            editor = "Calzolari, Nicoletta  and
              Choukri, Khalid  and
              Declerck, Thierry  and
              Loftsson, Hrafn  and
              Maegaard, Bente  and
              Mariani, Joseph  and
              Moreno, Asuncion  and
              Odijk, Jan  and
              Piperidis, Stelios",
            booktitle = "Proceedings of the Ninth International Conference on Language Resources and Evaluation ({LREC}'14)",
            month = may,
            year = "2014",
            address = "Reykjavik, Iceland",
            publisher = "European Language Resources Association (ELRA)",
            url = "http://www.lrec-conf.org/proceedings/lrec2014/pdf/1211_Paper.pdf",
            pages = "3712--3715",
            abstract = "This article presents the Polish Summaries Corpus, a new resource created to support the development and evaluation of the tools for automated single-document summarization of Polish. The Corpus contains a large number of manual summaries of news articles, with many independently created summaries for a single text. Such approach is supposed to overcome the annotator bias, which is often described as a problem during the evaluation of the summarization algorithms against a single gold standard. There are several summarizers developed specifically for Polish language, but their in-depth evaluation and comparison was impossible without a large, manually created corpus. We present in detail the process of text selection, annotation process and the contents of the corpus, which includes both abstract free-word summaries, as well as extraction-based summaries created by selecting text spans from the original document. Finally, we describe how that resource could be used not only for the evaluation of the existing summarization tools, but also for studies on the human summarization process in Polish language.",
        }""",
        n_samples={"test": 1080},
        avg_character_length={"test": 647.8},
    ),
    "ArguAna-PL": TaskMetadata(
        name="ArguAna-PL",
        description="ArguAna-PL",
        reference="https://huggingface.co/datasets/clarin-knext/arguana-pl",
        dataset={
            "path": "clarin-knext/arguana-pl",
            "revision": "63fc86750af76253e8c760fc9e534bbf24d260a2",
        },
        type="Retrieval",
        category="s2p",
        eval_splits=["test"],
        eval_langs=["pol-Latn"],
        main_score="ndcg_at_10",
        date=None,
        form=None,
        domains=['Web'],
        task_subtypes=None,
        license="CC-BY-4.0",
        socioeconomic_status=None,
        annotations_creators=None,
        dialect=None,
        text_creation=None,
        bibtex_citation="""@misc{wojtasik2024beirpl,
              title={BEIR-PL: Zero Shot Information Retrieval Benchmark for the Polish Language}, 
              author={Konrad Wojtasik and Vadim Shishkin and Kacper Wołowiec and Arkadiusz Janz and Maciej Piasecki},
              year={2024},
              eprint={2305.19840},
              archivePrefix={arXiv},
              primaryClass={cs.IR}
        }""",
        n_samples={'test': 1406, 'test_corpus': 8674},
        avg_character_length={'test': 1224.8, 'test_corpus': 1036.7},
    ),
    "DBPedia-PL": TaskMetadata(
        name="DBPedia-PL",
        description="DBpedia-Entity is a standard test collection for entity search over the DBpedia knowledge base",
        reference="https://github.com/iai-group/DBpedia-Entity/",
        dataset={
            "path": "clarin-knext/dbpedia-pl",
            "revision": "76afe41d9af165cc40999fcaa92312b8b012064a",
        },
        type="Retrieval",
        category="s2p",
        eval_splits=["test"],
        eval_langs=["pol-Latn"],
        main_score="ndcg_at_10",
        date=None,
        form=None,
        domains=['Encyclopaedic'],
        task_subtypes=None,
        license="CC-BY-SA-3.0",
        socioeconomic_status=None,
        annotations_creators=None,
        dialect=None,
        text_creation=None,
        bibtex_citation="""@inproceedings{Hasibi:2017:DVT,
         author =    {Hasibi, Faegheh and Nikolaev, Fedor and Xiong, Chenyan and Balog, Krisztian and Bratsberg, Svein Erik and Kotov, Alexander and Callan, Jamie},
         title =     {DBpedia-Entity V2: A Test Collection for Entity Search},
         booktitle = {Proceedings of the 40th International ACM SIGIR Conference on Research and Development in Information Retrieval},
         series =    {SIGIR '17},
         year =      {2017},
         pages =     {1265--1268},
         doi =       {10.1145/3077136.3080751},
         publisher = {ACM}
        }""",
        n_samples={'test': 467, 'test_corpus': 4635922},
        avg_character_length={'test': 34.7, 'test_corpus': 291.3},
    ),
    "FiQA-PL": TaskMetadata(
        name="FiQA-PL",
        description="Financial Opinion Mining and Question Answering",
        reference="https://sites.google.com/view/fiqa/",
        dataset={
            "path": "clarin-knext/fiqa-pl",
            "revision": "2e535829717f8bf9dc829b7f911cc5bbd4e6608e",
        },
        type="Retrieval",
        category="s2p",
        eval_splits=["test"],
        eval_langs=["pol-Latn"],
        main_score="ndcg_at_10",
        date=None,
        form=None,
        domains=['Web'],
        task_subtypes=None,
        license="Not specified",
        socioeconomic_status=None,
        annotations_creators=None,
        dialect=None,
        text_creation=None,
        bibtex_citation="""@inproceedings{
            thakur2021beir,
            title={{BEIR}: A Heterogeneous Benchmark for Zero-shot Evaluation of Information Retrieval Models},
            author={Nandan Thakur and Nils Reimers and Andreas R{\"u}ckl{\'e} and Abhishek Srivastava and Iryna Gurevych},
            booktitle={Thirty-fifth Conference on Neural Information Processing Systems Datasets and Benchmarks Track (Round 2)},
            year={2021},
            url={https://openreview.net/forum?id=wCu6T5xFjeJ}
        }""",
        n_samples={'test': 6648, 'test_corpus': 57638},
        avg_character_length={'test': 69.1, 'test_corpus': 795.2},
    ),
    "HotpotQA-PL": TaskMetadata(
        name="HotpotQA-PL",
        description="HotpotQA is a question answering dataset featuring natural, multi-hop questions, with strong supervision for supporting facts to enable more explainable question answering systems.",
        reference="https://hotpotqa.github.io/",
        dataset={
            "path": "clarin-knext/hotpotqa-pl",
            "revision": "a0bd479ac97b4ccb5bd6ce320c415d0bb4beb907",
        },
        type="Retrieval",
        category="s2p",
        eval_splits=["test"],
        eval_langs=["pol-Latn"],
        main_score="ndcg_at_10",
        date=None,
        form=None,
        domains=["Encyclopaedic"],
        task_subtypes=None,
        license="CC-BY-SA-4.0",
        socioeconomic_status=None,
        annotations_creators=None,
        dialect=None,
        text_creation=None,
        bibtex_citation="""@misc{wojtasik2024beirpl,
              title={BEIR-PL: Zero Shot Information Retrieval Benchmark for the Polish Language}, 
              author={Konrad Wojtasik and Vadim Shishkin and Kacper Wołowiec and Arkadiusz Janz and Maciej Piasecki},
              year={2024},
              eprint={2305.19840},
              archivePrefix={arXiv},
              primaryClass={cs.IR}
        }""",
        n_samples={'test': 97852, 'test_corpus': 5233329},
        avg_character_length={'test': 107.6, 'test_corpus': 271.7},
    ),
    "MSMARCO-PL": TaskMetadata(
        name="MSMARCO-PL",
        description="MS MARCO is a collection of datasets focused on deep learning in search",
        reference="https://microsoft.github.io/msmarco/",
        dataset={
            "path": "clarin-knext/msmarco-pl",
            "revision": "8634c07806d5cce3a6138e260e59b81760a0a640",
        },
        type="Retrieval",
        category="s2p",
        eval_splits=["test"],
        eval_langs=["pol-Latn"],
        main_score="ndcg_at_10",
        date=None,
        form=None,
        domains=["Web"],
        task_subtypes=None,
        license="MIT",
        socioeconomic_status=None,
        annotations_creators=None,
        dialect=None,
        text_creation=None,
        bibtex_citation=""""@misc{wojtasik2024beirpl,
              title={BEIR-PL: Zero Shot Information Retrieval Benchmark for the Polish Language}, 
              author={Konrad Wojtasik and Vadim Shishkin and Kacper Wołowiec and Arkadiusz Janz and Maciej Piasecki},
              year={2024},
              eprint={2305.19840},
              archivePrefix={arXiv},
              primaryClass={cs.IR}
        }""",
        n_samples={'test': 520362, 'test_corpus': 8841823},
        avg_character_length={'test': 35.2, 'test_corpus': 349.4},
    ),
    "NFCorpus-PL": TaskMetadata(
        name="NFCorpus-PL",
        description="NFCorpus: A Full-Text Learning to Rank Dataset for Medical Information Retrieval",
        reference="https://www.cl.uni-heidelberg.de/statnlpgroup/nfcorpus/",
        dataset={
            "path": "clarin-knext/nfcorpus-pl",
            "revision": "9a6f9567fda928260afed2de480d79c98bf0bec0",
        },
        type="Retrieval",
        category="s2p",
        eval_splits=["test"],
        eval_langs=["pol-Latn"],
        main_score="ndcg_at_10",
        date=None,
        form=None,
        domains=["Medical"],
        task_subtypes=None,
        license="Not specified",
        socioeconomic_status=None,
        annotations_creators=None,
        dialect=None,
        text_creation=None,
        bibtex_citation="""@misc{wojtasik2024beirpl,
              title={BEIR-PL: Zero Shot Information Retrieval Benchmark for the Polish Language}, 
              author={Konrad Wojtasik and Vadim Shishkin and Kacper Wołowiec and Arkadiusz Janz and Maciej Piasecki},
              year={2024},
              eprint={2305.19840},
              archivePrefix={arXiv},
              primaryClass={cs.IR}
        }""",
        n_samples={'test': 3237, 'test_corpus': 3633},
        avg_character_length={'test': 24.6, 'test_corpus': 1554.3},
    ),
    "NQ-PL": TaskMetadata(
        name="NQ-PL",
        description="Natural Questions: A Benchmark for Question Answering Research",
        reference="https://ai.google.com/research/NaturalQuestions/",
        dataset={
            "path": "clarin-knext/nq-pl",
            "revision": "f171245712cf85dd4700b06bef18001578d0ca8d",
        },
        type="Retrieval",
        category="s2p",
        eval_splits=["test"],
        eval_langs=["pol-Latn"],
        main_score="ndcg_at_10",
        date=None,
        form=None,
        domains=["Web"],
        task_subtypes=None,
        license="CC-BY-SA-3.0",
        socioeconomic_status=None,
        annotations_creators=None,
        dialect=None,
        text_creation=None,
        bibtex_citation="""@misc{wojtasik2024beirpl,
              title={BEIR-PL: Zero Shot Information Retrieval Benchmark for the Polish Language}, 
              author={Konrad Wojtasik and Vadim Shishkin and Kacper Wołowiec and Arkadiusz Janz and Maciej Piasecki},
              year={2024},
              eprint={2305.19840},
              archivePrefix={arXiv},
              primaryClass={cs.IR}
        }""",
        n_samples={'test': 3452, 'test_corpus': 2681468},
        avg_character_length={'test': 48.3, 'test_corpus': 480.9},
    ),
    "Quora-PL": TaskMetadata(
        name="Quora-PL",
        description="QuoraRetrieval is based on questions that are marked as duplicates on the Quora platform. Given a question, find other (duplicate) questions.",
        reference="https://quoradata.quora.com/First-Quora-Dataset-Release-Question-Pairs",
        dataset={
            "path": "clarin-knext/quora-pl",
            "revision": "0be27e93455051e531182b85e85e425aba12e9d4",
        },
        type="Retrieval",
        category="s2s",
        eval_splits=["validation", "test"],
        eval_langs=["pol-Latn"],
        main_score="ndcg_at_10",
        date=None,
        form=None,
        domains=["Web"],
        task_subtypes=None,
        license="Not specified",
        socioeconomic_status=None,
        annotations_creators=None,
        dialect=None,
        text_creation=None,
        bibtex_citation=""""@misc{wojtasik2024beirpl,
              title={BEIR-PL: Zero Shot Information Retrieval Benchmark for the Polish Language}, 
              author={Konrad Wojtasik and Vadim Shishkin and Kacper Wołowiec and Arkadiusz Janz and Maciej Piasecki},
              year={2024},
              eprint={2305.19840},
              archivePrefix={arXiv},
              primaryClass={cs.IR}
        }""",
        n_samples={'test': 15000, 'test_corpus': 522931},
        avg_character_length={'test': 54.6, 'test_corpus': 65.8},
    ),
    "SCIDOCS-PL": TaskMetadata(
        name="SCIDOCS-PL",
        description="SciDocs, a new evaluation benchmark consisting of seven document-level tasks ranging from citation prediction, to document classification and recommendation.",
        reference="https://allenai.org/data/scidocs",
        dataset={
            "path": "clarin-knext/scidocs-pl",
            "revision": "45452b03f05560207ef19149545f168e596c9337",
        },
        type="Retrieval",
        category="s2p",
        eval_splits=["test"],
        eval_langs=["pol-Latn"],
        main_score="ndcg_at_10",
        date=None,
        form=None,
        domains=["Academic"],
        task_subtypes=None,
        license="GNU-3.0",
        socioeconomic_status=None,
        annotations_creators=None,
        dialect=None,
        text_creation=None,
        bibtex_citation="""@misc{wojtasik2024beirpl,
              title={BEIR-PL: Zero Shot Information Retrieval Benchmark for the Polish Language}, 
              author={Konrad Wojtasik and Vadim Shishkin and Kacper Wołowiec and Arkadiusz Janz and Maciej Piasecki},
              year={2024},
              eprint={2305.19840},
              archivePrefix={arXiv},
              primaryClass={cs.IR}
        }""",
        n_samples={'test': 1000, 'test_corpus': 25657},
        avg_character_length={'test': 80.7, 'test_corpus': 1191.0},
    ),
    "SciFact-PL": TaskMetadata(
        name="SciFact-PL",
        description="SciFact verifies scientific claims using evidence from the research literature containing scientific paper abstracts.",
        reference="https://github.com/allenai/scifact",
        dataset={
            "path": "clarin-knext/scifact-pl",
            "revision": "47932a35f045ef8ed01ba82bf9ff67f6e109207e",
        },
        type="Retrieval",
        category="s2p",
        eval_splits=["test"],
        eval_langs=["pol-Latn"],
        main_score="ndcg_at_10",
        date=None,
        form=None,
        domains=["Academic"],
        task_subtypes=None,
        license="CC-BY-NC-2.0",
        socioeconomic_status=None,
        annotations_creators=None,
        dialect=None,
        text_creation=None,
        bibtex_citation="""@misc{wojtasik2024beirpl,
              title={BEIR-PL: Zero Shot Information Retrieval Benchmark for the Polish Language}, 
              author={Konrad Wojtasik and Vadim Shishkin and Kacper Wołowiec and Arkadiusz Janz and Maciej Piasecki},
              year={2024},
              eprint={2305.19840},
              archivePrefix={arXiv},
              primaryClass={cs.IR}
        }""",
        n_samples={'test': 1109, 'test_corpus': 5183},
        avg_character_length={'test': 93.9, 'test_corpus': 1450.6},
    ),
    "TRECCOVID-PL": TaskMetadata(
        name="TRECCOVID-PL",
        description="TRECCOVID is an ad-hoc search challenge based on the COVID-19 dataset containing scientific articles related to the COVID-19 pandemic.",
        reference="https://ir.nist.gov/covidSubmit/index.html",
        dataset={
            "path": "clarin-knext/trec-covid-pl",
            "revision": "81bcb408f33366c2a20ac54adafad1ae7e877fdd",
        },
        type="Retrieval",
        category="s2p",
        eval_splits=["test"],
        eval_langs=["pol-Latn"],
        main_score="ndcg_at_10",
        date=None,
        form=None,
        domains=["Medical"],
        task_subtypes=None,
        license="License Agreement",
        socioeconomic_status=None,
        annotations_creators=None,
        dialect=None,
        text_creation=None,
        bibtex_citation="""@misc{wojtasik2024beirpl,
              title={BEIR-PL: Zero Shot Information Retrieval Benchmark for the Polish Language}, 
              author={Konrad Wojtasik and Vadim Shishkin and Kacper Wołowiec and Arkadiusz Janz and Maciej Piasecki},
              year={2024},
              eprint={2305.19840},
              archivePrefix={arXiv},
              primaryClass={cs.IR}
        }""",
        n_samples={'test': 50, 'test_corpus': 171332},
        avg_character_length={'test': 69.4, 'test_corpus': 1060.2},
    ),
    "SciDefRetrieval": TaskMetadata(
        name="SciDefRetrieval",
        description="Finding definitions of a word or concept from chemistry, physics, mathematics, geology and "
                    "social science coursebooks.",
        reference="https://huggingface.co/datasets/rafalposwiata/open-coursebooks-pl",
        dataset={
            "path": "PL-MTEB/scidef",
            "revision": "4755de8baebc07bed0c60cec9f796e9a346600cb",
        },
        type="Retrieval",
        category="s2p",
        eval_splits=["test"],
        eval_langs=["pol-Latn"],
        main_score="ndcg_at_10",
        date=None,
        form=None,
        domains=["Academic"],
        task_subtypes=None,
        license="cc-by-sa-4.0",
        socioeconomic_status=None,
        annotations_creators=None,
        dialect=None,
        text_creation=None,
        bibtex_citation=None,
        n_samples={'test': 679, 'test_corpus': 679},
        avg_character_length={'test': 52.6, 'test_corpus': 365.0},
    ),
    "SICK-R-PL": TaskMetadata(
        name="SICK-R-PL",
        dataset={
            "path": "PL-MTEB/sickr-pl-sts",
            "revision": "fd5c2441b7eeff8676768036142af4cfa42c1339",
        },
        description="Polish version of SICK dataset for textual relatedness.",
        reference="https://aclanthology.org/2020.lrec-1.207",
        type="STS",
        category="s2s",
        eval_splits=["test"],
        eval_langs=["pol-Latn"],
        main_score="cosine_spearman",
        date=("2018-01-01", "2019-09-01"),  # rough estimate
        form=["written"],
        domains=["Web"],
        task_subtypes=None,
        license="CC-BY-NC-SA-3.0",
        socioeconomic_status="mixed",
        annotations_creators="human-annotated",
        dialect=[],
        text_creation="human-translated and localized",
        bibtex_citation="""
        @inproceedings{dadas-etal-2020-evaluation,
            title = "Evaluation of Sentence Representations in {P}olish",
            author = "Dadas, Slawomir  and
              Pere{\l}kiewicz, Micha{\l}  and
              Po{\'s}wiata, Rafa{\l}",
            editor = "Calzolari, Nicoletta  and
              B{\'e}chet, Fr{\'e}d{\'e}ric  and
              Blache, Philippe  and
              Choukri, Khalid  and
              Cieri, Christopher  and
              Declerck, Thierry  and
              Goggi, Sara  and
              Isahara, Hitoshi  and
              Maegaard, Bente  and
              Mariani, Joseph  and
              Mazo, H{\'e}l{\`e}ne  and
              Moreno, Asuncion  and
              Odijk, Jan  and
              Piperidis, Stelios",
            booktitle = "Proceedings of the Twelfth Language Resources and Evaluation Conference",
            month = may,
            year = "2020",
            address = "Marseille, France",
            publisher = "European Language Resources Association",
            url = "https://aclanthology.org/2020.lrec-1.207",
            pages = "1674--1680",
            language = "English",
            ISBN = "979-10-95546-34-4",
        }
        """,
        n_samples={"test": 4910},
        avg_character_length={"test": 42.8},
    ),
    "CDSC-R": TaskMetadata(
        name="CDSC-R",
        dataset={
            "path": "PL-MTEB/cdscr-sts",
            "revision": "1cd6abbb00df7d14be3dbd76a7dcc64b3a79a7cd",
        },
        description="Compositional Distributional Semantics Corpus for textual relatedness.",
        reference="https://aclanthology.org/P17-1073.pdf",
        type="STS",
        category="s2s",
        eval_splits=["test"],
        eval_langs=["pol-Latn"],
        main_score="cosine_spearman",
        date=("2016-01-01", "2017-04-01"),  # rough estimate
        form=["written"],
        domains=["Web"],
        task_subtypes=None,
        license="CC-BY-NC-SA-4.0",
        socioeconomic_status="mixed",
        annotations_creators="human-annotated",
        dialect=[],
        text_creation="human-translated and localized",
        bibtex_citation="""
        @inproceedings{wroblewska-krasnowska-kieras-2017-polish,
            title = "{P}olish evaluation dataset for compositional distributional semantics models",
            author = "Wr{\'o}blewska, Alina  and
              Krasnowska-Kiera{\'s}, Katarzyna",
            editor = "Barzilay, Regina  and
              Kan, Min-Yen",
            booktitle = "Proceedings of the 55th Annual Meeting of the Association for Computational Linguistics (Volume 1: Long Papers)",
            month = jul,
            year = "2017",
            address = "Vancouver, Canada",
            publisher = "Association for Computational Linguistics",
            url = "https://aclanthology.org/P17-1073",
            doi = "10.18653/v1/P17-1073",
            pages = "784--792",
        }
        """,
        n_samples={"test": 1000},
        avg_character_length={"test": 75.24},
    ),
    "STS22": TaskMetadata(
        name="STS22",
        dataset={
            "path": "mteb/sts22-crosslingual-sts",
            "revision": "de9d86b3b84231dc21f76c7b7af1f28e2f57f6e3",
        },
        description="SemEval 2022 Task 8: Multilingual News Article Similarity",
        reference="https://competitions.codalab.org/competitions/33835",
        type="STS",
        category="p2p",
        eval_splits=["test"],
        eval_langs=_STS22_LANGUAGES,
        main_score="cosine_spearman",
        date=("2020-01-01", "2020-06-11"),
        form=["written"],
        domains=["News"],
        task_subtypes=[],
        license="Not specified",
        socioeconomic_status="mixed",
        annotations_creators="human-annotated",
        dialect=[],
        text_creation="found",
        bibtex_citation="""@inproceedings{chen-etal-2022-semeval,
            title = "{S}em{E}val-2022 Task 8: Multilingual news article similarity",
            author = {Chen, Xi  and
              Zeynali, Ali  and
              Camargo, Chico  and
              Fl{\"o}ck, Fabian  and
              Gaffney, Devin  and
              Grabowicz, Przemyslaw  and
              Hale, Scott  and
              Jurgens, David  and
              Samory, Mattia},
            editor = "Emerson, Guy  and
              Schluter, Natalie  and
              Stanovsky, Gabriel  and
              Kumar, Ritesh  and
              Palmer, Alexis  and
              Schneider, Nathan  and
              Singh, Siddharth  and
              Ratan, Shyam",
            booktitle = "Proceedings of the 16th International Workshop on Semantic Evaluation (SemEval-2022)",
            month = jul,
            year = "2022",
            address = "Seattle, United States",
            publisher = "Association for Computational Linguistics",
            url = "https://aclanthology.org/2022.semeval-1.155",
            doi = "10.18653/v1/2022.semeval-1.155",
            pages = "1094--1106",
        }""",
        n_samples={"test": 8056},
        avg_character_length={"test": 1993.6},
    )
}


def generate_retrieval_stats():
    results = {}
    for task, metadata in tasks_metadata.items():
        if metadata.type == "Retrieval":
            def count_avg_length(dataset):
                return sum([len(text) for text in dataset['text']])

            queries = datasets.load_dataset(metadata.dataset["path"], "queries", ignore_verifications=True)["queries"]
            corpus = datasets.load_dataset(metadata.dataset["path"], "corpus", ignore_verifications=True)["corpus"]
            stats = {
                "test": queries.num_rows,
                "test_corpus": corpus.num_rows
            }
            len_stats = {
                "test": round(count_avg_length(queries) / queries.num_rows, 1),
                "test_corpus": round(count_avg_length(corpus) / corpus.num_rows, 1)
            }
            results[task] = f"n_samples={stats},\navg_character_length={len_stats},"
    for t, s in results.items():
        print(f'{t}\n{s}')


def get_value(field: any, field_type: any, metadata_type: str = None) -> str:
    if field is None:
        return ""
    if field_type == list:
        return ', '.join(field)
    elif field_type == dict:
        if metadata_type == 'Retrieval':
            return "\makecell[l]{q: " + str(field["test"]) + " \\\\c: " + str(field["test_corpus"]) + "}"
        elif metadata_type == 'Classification':
            return "\makecell[l]{trn: " + str(field["train"]) + " \\\\tst: " + str(field["test"]) + "}"
        else:
            return "tst: " + str(field["test"])
    else:
        return field


def prepare_task_name(task: str) -> str:
    task_name = task \
        .replace("Classification", "") \
        .replace("Clustering", "") \
        .replace("Retrieval", "")
    return "\makecell[l]{" + task_name + " \\\\  }"


def prepare_link(path: str) -> str:
    return '\\href{https://huggingface.co/datasets/' + path + '}{\\url{' + path.replace("_", "\\_") + '}} '


def generate_tasks_details_table(table_format: str = 'psql'):
    columns = ['Task', 'Link', 'Domain', 'Licence', 'No. examples', 'Avg. length']
    rows = []
    for task, metadata in tasks_metadata.items():
        print(task)
        rows.append({
            'Task': prepare_task_name(task),
            'Link': prepare_link(metadata.dataset["path"]),
            'Domain': get_value(metadata.domains, list),
            'Licence': get_value(metadata.license, str).upper(),
            'No. examples': get_value(metadata.n_samples, dict, metadata.type),
            'Avg. length': get_value(metadata.avg_character_length, dict, metadata.type)
        })

    df = pd.DataFrame(rows, columns=columns)
    tab = tabulate(df, headers='keys', tablefmt=table_format, showindex=False)
    print(tab)


if __name__ == '__main__':
    # generate_retrieval_stats()
    generate_tasks_details_table()
